site_name: FastAPI HyperModel
theme:
  name: material

repo_name: jtc42/fastapi-hypermodel
repo_url: https://github.com/jtc42/fastapi-hypermodel

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

docs_dir: './docs'

nav:
  - Home: 'index.md'
  - Basic Usage: 'basics.md'
  - Advanced Usage: 'advanced.md'
  - Extending FastAPI-HyperModel: 'extending.md'
