[tool.poetry]
authors = ["Joel Collins <joel.collins@renalregistry.nhs.uk>"]
description = ""
name = "fastapi-hypermodel"
version = "0.1.0"

[tool.poetry.dependencies]
python = "^3.6"
fastapi = "^0.63.0"
pydantic = "^1.7.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = {version = "^20.8b1", allow-prereleases = true}
uvicorn = "^0.13.4"
isort = "^5.7.0"
pylint = "^2.6.2"
requests = "^2.25.1"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
